services:
  postgres:
    container_name: workopia-db
    environment:
      - POSTGRES_USER=workopia
      - POSTGRES_PASSWORD=workopia
      - POSTGRES_DB=Workopia
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_workopia:/var/lib/postgresql/data/

  #  workopia:
  #   ports:
  #     - "5000:5000"  # HTTP port
  #     - "5050:5050"  # HTTPS port
  #   environment:
  #     - ASPNETCORE_URLS=https://+:5050;http://+:5000
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=awesomepass
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/eshopmodularmodulith.pfx
  #   depends_on:
  #     - eshopdb
  #   volumes:
  #     - ${USERPROFILE}/.aspnet/https:/https:ro
